version: '3.8'

services:
  frontend-tienda-alimentacion:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
      target: build-stage
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ../../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - tienda-net

networks:
  tienda-net:
    external: true
