"""Add refresh tokens table

Revision ID: 61c82d9d4623
Revises: c89185a18b44
Create Date: 2025-11-05 11:26:39.741098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c82d9d4623'
down_revision = 'c89185a18b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
