"""Add wishlist table

Revision ID: c9fb79b42932
Revises: 8b30e34f49e1
Create Date: 2025-11-06 17:05:34.869996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9fb79b42932'
down_revision = '8b30e34f49e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_product_wishlist_unique', 'wishlist_items', ['user_id', 'product_id'], unique=True)
    op.create_index('idx_user_wishlist', 'wishlist_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_id'), 'wishlist_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_items_id'), table_name='wishlist_items')
    op.drop_index('idx_user_wishlist', table_name='wishlist_items')
    op.drop_index('idx_user_product_wishlist_unique', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    # ### end Alembic commands ###
